### ISSUE TITLE
cesium-terrain-server:latest error on docker hub

### ISSUE THREAD

**Issue by muratkendir** [geo-data/cesium-terrain-server#15]
I was using build cesium-terrain-server on docker hub until previous week. This week i noticed that automated docker build does not work properly, despite every configuration of my terrain (in quantized-mesh format) file seems right just as it is explained in Bert's tutorial page 
(https://bertt.wordpress.com/2018/11/26/visualizing-terrains-with-cesium-ii/).

So, whenever i test my terrain file it is giving following error: **"The tileset `tiles` does not exist"**

Do you know anything about this docker hub problem or do you have any suggestion about this error?

**Comment by raycrummey** [comment]
Hey murat.  I noticed an issue as well.  If you are stuck you can pull by the sha to get one that works.

docker pull geodata/cesium-terrain-server@sha256:52c4d23f87caf84de74ebf9b79da2fb2bd6ca3c545b7d08256d15a6c05781632

**Comment by muratkendir** [comment]
Thank you Ray, but unfortunately i couldn't run this repository too. I am not familiar about this docker mount directory and default web directory, but i tried these commands:
- Actual file location:
- "**D:\gisdata\nederland\tilesets\terrain\layer.json**"
-My command:
- docker run -p 8080:8000 -v **D:/gisdata/nederland/tilesets/terrain:/data/tilesets/terrain --env -base-terrain-url="/tilesets"** geodata/cesium-terrain-server@sha256:52c4d23f87caf84de74ebf9b79da2fb2bd6ca3c545b7d08256d15a6c05781632
- localhost:8080 works with an empty world terrain, but terrain files or layer.json does not response to my command:
- wget **http://localhost:8080/tilesets/terrain/layer.json**

Do you have any suggestions?

**Comment by muratkendir** [comment]
Aha, ok i solved my problem. I only missed to create "tiles" folder as parent folder to my terrain files. ctb-tile commands has been creating this folder automatically, but i was tried to mount my terrain path manually to the cesium terrain server.  So changing file location as following path solved my problem:
**D:\gisdata\nederland\tilesets\terrain\tiles\layer.json**
