### ISSUE TITLE
Not able to view terrain data

### ISSUE THREAD

**Issue by SurajitChowbey** [geo-data/cesium-terrain-server#17]
I'm using docker in windows 10.

I have used the following steps:
`docker run -p 8080:8000 -v "${pwd}/tilesets/terrain:/data/tilesets/terrain" geodata/cesium-terrain-server`

After this I'm accessing it in: [http://localhost:8080](http://localhost:8080)

Powershell:
![console](https://user-images.githubusercontent.com/18625898/56804423-57fff300-6843-11e9-8ea3-2a465370c206.JPG)

Terrain data:

![terrain_data](https://user-images.githubusercontent.com/18625898/56804424-58988980-6843-11e9-98c8-93fe60c8557b.JPG)

Browser error:
![access_error](https://user-images.githubusercontent.com/18625898/56804442-664e0f00-6843-11e9-8a9f-392467dac7fa.JPG)

**Comment by Klingseis** [comment]
Hey @SurajitChowbey,
I'm not sure if this might be the reason, but did you already try to leave out the "terrain" in the request path?
So instead accessing "http://localhost:8080/tilesets/terrain/test", try this: "http://localhost:8080/tilesets/test".

Hope this helps you.

**Comment by SurajitChowbey** [comment]
Thank you, it solved the issue.

**Comment by chaitanyajalluri** [comment]
> Thank you, it solved the issue.



> Hey @SurajitChowbey,
> I'm not sure if this might be the reason, but did you already try to leave out the "terrain" in the request path?
> So instead accessing "http://localhost:8080/tilesets/terrain/test", try this: "http://localhost:8080/tilesets/test".
> 
> Hope this helps you.

In my case i am getting 404 page not found error while trying http://localhost:9000/tilesets/test and
http://localhost:9000/tilesets/terrain/test , and empty globe in case of http://localhost:8080.

**Comment by Klingseis** [comment]
And your terrainserver is running on port 9000? Did you create the layer.json-file?

**Comment by chaitanyajalluri** [comment]
thanks a lot. my issue is resolved
