### ISSUE TITLE
Logic inverted in TilesetStatus function in fs.go

### ISSUE THREAD

**Issue by GeorgeDewar** [geo-data/cesium-terrain-server#2]
We have noticed a problem where if a tileset exists, the server will complain that it does not. Confusingly, the logic to check if the tileset exists is invoked *only* if the file requested does *not* exist, such as when asking for a nonexistant base layer or layers.json.

The problem seems to be this code:

```
func (this *Store) TilesetStatus(tileset string) (status stores.TilesetStatus) {
	// check whether the tile directory exists
	_, err := os.Stat(filepath.Join(this.root, tileset))
	if err != nil {
		if os.IsNotExist(err) {
			return stores.FOUND
		}
	}

	return stores.NOT_FOUND
}
```

It returns FOUND if there is an error, and NOT_FOUND if there is no error!

**Comment by homme** [comment]
You are absolutely right - thank you! Commit c92940f fixes this which I have tagged as [v0.5.1](https://github.com/geo-data/cesium-terrain-server/releases/tag/v0.5.1).
