### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by InesKhandelwal** [geo-data/cesium-terrain-server#3]
On executing the install command
gis@Vaio:~$ go install github.com/geo-data/cesium-terrain-server

I get this error:
can't load package: package github.com/geo-data/cesium-terrain-server: no buildable Go source files in /home/gis/gocode/src/github.com/geo-data/cesium-terrain-server

My data connection seems to be fine. Where are the source files to build.
I am executing from my home directory in Ubuntu LTS 14.04 and go is installed and working.

**Comment by homme** [comment]
The install command in the README was incorrect: I've updated it in commit 4a6a408 as follows:

    go get github.com/geo-data/cesium-terrain-server/cmd/cesium-terrain-server
